### ISSUE TITLE
old version of bower

### ISSUE THREAD

**Issue by SimonKenyonShepard** [chrisgladd/grunt-phantomcss#38] opened 2015-02-25 11:47 UTC
bower phantomcss#f0846511d9e1e55aa160aaab84e2a150bd3a5a41            error Arguments to path.join must be strings

Stack trace:
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at GitHubResolver.GitResolver._cleanup (/Users/sshepard/rzf/grunt-phantomcss/node_modules/bower/lib/core/resolvers/GitResolver.js:158:26)
    at /Users/sshepard/rzf/grunt-phantomcss/node_modules/bower/lib/core/resolvers/GitResolver.js:66:25
    at Promise.apply (/Users/sshepard/rzf/grunt-phantomcss/node_modules/bower/node_modules/q/q.js:1122:26)
    at Promise.promise.promiseDispatch (/Users/sshepard/rzf/grunt-phantomcss/node_modules/bower/node_modules/q/q.js:752:41)
    at /Users/sshepard/rzf/grunt-phantomcss/node_modules/bower/node_modules/q/q.js:1337:14
    at flush (/Users/sshepard/rzf/grunt-phantomcss/node_modules/bower/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:419:13)

I fixed this by checking out locally and upgrading the version of bower to the lastest in the package.json. If you want I can fork and push?

**Comment by lazd** [comment] 2015-03-05 03:16
#36 fixes this, @chrisgladd can you do some house keeping and get the dependencies up to date so this module can be used again?

**Comment by lazd** [comment] 2015-03-05 03:17
Duplicate of #35 and #31

**Closed** 2016-03-31 08:20 UTC
